# apiVersion: elbv2.k8s.aws/v1beta1
# kind: TargetGroupBinding
# metadata:
#   name: frontend
#   namespace: expense
# spec:
#   serviceRef:
#     name: frontend # route traffic to the awesome-service
#     port: 80
#   targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:339713021737:loadbalancer/app/expense-dev-ingress-alb/a8a995307b9c7e59